model_name_or_path: "/share/home/jfliang/Weights/llava-onevision-qwen2-7b-ov"
beta: 0.1
output_dir: null  # to be set by the script
bf16: true
fix_vit: true
num_train_epochs: 3
per_device_train_batch_size: 1
per_device_eval_batch_size: 4
gradient_accumulation_steps: 8
# evaluation_strategy: "epoch"
save_strategy: "steps"
save_steps: 500
save_total_limit: 5
learning_rate: 0.00001
weight_decay: 0.05
ddp_find_unused_parameters: false
adam_beta2: 0.98
warmup_ratio: 0.1
lr_scheduler_type: "cosine"
logging_steps: 10
mode: "perturbation_loss"
crop_mode: "crop_images_only"
report_to: wandb
model_max_length: 2048
max_frames_num: 8
gradient_checkpointing: true
use_lora: true
bf16: true
tf32: true
logging_first_step: true
remove_unused_columns: false
lora_r: 64  
lora_alpha: 128 
lora_target_modules: all-linear 
gradient_checkpointing_kwargs: {"use_reentrant": False}
dataset_path: /share/home/jfliang/Project/Hall/Video-mDPO/data/video_llava_hound_17k.json
run_name: mdpo_llavaov
output_dir: /share/home/jfliang/Project/Hall/Video-mDPO/checkpoint/llava-onevision-qwen2-mdpo-lora-mdpoloss-per-10k-crop-clear_text